// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BackingImageSpec struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Directory            string   `protobuf:"bytes,5,opt,name=directory,proto3" json:"directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackingImageSpec) Reset()         { *m = BackingImageSpec{} }
func (m *BackingImageSpec) String() string { return proto.CompactTextString(m) }
func (*BackingImageSpec) ProtoMessage()    {}
func (*BackingImageSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *BackingImageSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackingImageSpec.Unmarshal(m, b)
}
func (m *BackingImageSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackingImageSpec.Marshal(b, m, deterministic)
}
func (m *BackingImageSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackingImageSpec.Merge(m, src)
}
func (m *BackingImageSpec) XXX_Size() int {
	return xxx_messageInfo_BackingImageSpec.Size(m)
}
func (m *BackingImageSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_BackingImageSpec.DiscardUnknown(m)
}

var xxx_messageInfo_BackingImageSpec proto.InternalMessageInfo

func (m *BackingImageSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BackingImageSpec) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *BackingImageSpec) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BackingImageSpec) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BackingImageSpec) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

type BackingImageStatus struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	SendingReference     int32    `protobuf:"varint,3,opt,name=sending_reference,json=sendingReference,proto3" json:"sending_reference,omitempty"`
	SenderManagerAddress string   `protobuf:"bytes,4,opt,name=sender_manager_address,json=senderManagerAddress,proto3" json:"sender_manager_address,omitempty"`
	DownloadProgress     int32    `protobuf:"varint,5,opt,name=downloadProgress,proto3" json:"downloadProgress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackingImageStatus) Reset()         { *m = BackingImageStatus{} }
func (m *BackingImageStatus) String() string { return proto.CompactTextString(m) }
func (*BackingImageStatus) ProtoMessage()    {}
func (*BackingImageStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *BackingImageStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackingImageStatus.Unmarshal(m, b)
}
func (m *BackingImageStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackingImageStatus.Marshal(b, m, deterministic)
}
func (m *BackingImageStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackingImageStatus.Merge(m, src)
}
func (m *BackingImageStatus) XXX_Size() int {
	return xxx_messageInfo_BackingImageStatus.Size(m)
}
func (m *BackingImageStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BackingImageStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BackingImageStatus proto.InternalMessageInfo

func (m *BackingImageStatus) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *BackingImageStatus) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *BackingImageStatus) GetSendingReference() int32 {
	if m != nil {
		return m.SendingReference
	}
	return 0
}

func (m *BackingImageStatus) GetSenderManagerAddress() string {
	if m != nil {
		return m.SenderManagerAddress
	}
	return ""
}

func (m *BackingImageStatus) GetDownloadProgress() int32 {
	if m != nil {
		return m.DownloadProgress
	}
	return 0
}

type BackingImageResponse struct {
	Spec                 *BackingImageSpec   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Status               *BackingImageStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Deleted              bool                `protobuf:"varint,3,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BackingImageResponse) Reset()         { *m = BackingImageResponse{} }
func (m *BackingImageResponse) String() string { return proto.CompactTextString(m) }
func (*BackingImageResponse) ProtoMessage()    {}
func (*BackingImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *BackingImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackingImageResponse.Unmarshal(m, b)
}
func (m *BackingImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackingImageResponse.Marshal(b, m, deterministic)
}
func (m *BackingImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackingImageResponse.Merge(m, src)
}
func (m *BackingImageResponse) XXX_Size() int {
	return xxx_messageInfo_BackingImageResponse.Size(m)
}
func (m *BackingImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BackingImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BackingImageResponse proto.InternalMessageInfo

func (m *BackingImageResponse) GetSpec() *BackingImageSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *BackingImageResponse) GetStatus() *BackingImageStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BackingImageResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type PullRequest struct {
	Spec                 *BackingImageSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetSpec() *BackingImageSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

type DeleteRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListResponse struct {
	BackingImages        map[string]*BackingImageResponse `protobuf:"bytes,1,rep,name=backing_images,json=backingImages,proto3" json:"backing_images,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetBackingImages() map[string]*BackingImageResponse {
	if m != nil {
		return m.BackingImages
	}
	return nil
}

type SendRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ToAddress            string   `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendRequest) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

type SyncRequest struct {
	BackingImageSpec     *BackingImageSpec `protobuf:"bytes,1,opt,name=backing_image_spec,json=backingImageSpec,proto3" json:"backing_image_spec,omitempty"`
	FromHost             string            `protobuf:"bytes,2,opt,name=from_host,json=fromHost,proto3" json:"from_host,omitempty"`
	ToHost               string            `protobuf:"bytes,3,opt,name=to_host,json=toHost,proto3" json:"to_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SyncRequest) Reset()         { *m = SyncRequest{} }
func (m *SyncRequest) String() string { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()    {}
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *SyncRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncRequest.Unmarshal(m, b)
}
func (m *SyncRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncRequest.Marshal(b, m, deterministic)
}
func (m *SyncRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRequest.Merge(m, src)
}
func (m *SyncRequest) XXX_Size() int {
	return xxx_messageInfo_SyncRequest.Size(m)
}
func (m *SyncRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRequest proto.InternalMessageInfo

func (m *SyncRequest) GetBackingImageSpec() *BackingImageSpec {
	if m != nil {
		return m.BackingImageSpec
	}
	return nil
}

func (m *SyncRequest) GetFromHost() string {
	if m != nil {
		return m.FromHost
	}
	return ""
}

func (m *SyncRequest) GetToHost() string {
	if m != nil {
		return m.ToHost
	}
	return ""
}

type OwnershipTransferStartResponse struct {
	ReadyBackingImages   map[string]*BackingImageSpec `protobuf:"bytes,1,rep,name=ready_backing_images,json=readyBackingImages,proto3" json:"ready_backing_images,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *OwnershipTransferStartResponse) Reset()         { *m = OwnershipTransferStartResponse{} }
func (m *OwnershipTransferStartResponse) String() string { return proto.CompactTextString(m) }
func (*OwnershipTransferStartResponse) ProtoMessage()    {}
func (*OwnershipTransferStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *OwnershipTransferStartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnershipTransferStartResponse.Unmarshal(m, b)
}
func (m *OwnershipTransferStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnershipTransferStartResponse.Marshal(b, m, deterministic)
}
func (m *OwnershipTransferStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnershipTransferStartResponse.Merge(m, src)
}
func (m *OwnershipTransferStartResponse) XXX_Size() int {
	return xxx_messageInfo_OwnershipTransferStartResponse.Size(m)
}
func (m *OwnershipTransferStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnershipTransferStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OwnershipTransferStartResponse proto.InternalMessageInfo

func (m *OwnershipTransferStartResponse) GetReadyBackingImages() map[string]*BackingImageSpec {
	if m != nil {
		return m.ReadyBackingImages
	}
	return nil
}

type OwnershipTransferConfirmRequest struct {
	ReadyBackingImages   map[string]*BackingImageSpec `protobuf:"bytes,1,rep,name=ready_backing_images,json=readyBackingImages,proto3" json:"ready_backing_images,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *OwnershipTransferConfirmRequest) Reset()         { *m = OwnershipTransferConfirmRequest{} }
func (m *OwnershipTransferConfirmRequest) String() string { return proto.CompactTextString(m) }
func (*OwnershipTransferConfirmRequest) ProtoMessage()    {}
func (*OwnershipTransferConfirmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *OwnershipTransferConfirmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnershipTransferConfirmRequest.Unmarshal(m, b)
}
func (m *OwnershipTransferConfirmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnershipTransferConfirmRequest.Marshal(b, m, deterministic)
}
func (m *OwnershipTransferConfirmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnershipTransferConfirmRequest.Merge(m, src)
}
func (m *OwnershipTransferConfirmRequest) XXX_Size() int {
	return xxx_messageInfo_OwnershipTransferConfirmRequest.Size(m)
}
func (m *OwnershipTransferConfirmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnershipTransferConfirmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OwnershipTransferConfirmRequest proto.InternalMessageInfo

func (m *OwnershipTransferConfirmRequest) GetReadyBackingImages() map[string]*BackingImageSpec {
	if m != nil {
		return m.ReadyBackingImages
	}
	return nil
}

type VersionResponse struct {
	Version                          string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	GitCommit                        string   `protobuf:"bytes,2,opt,name=gitCommit,proto3" json:"gitCommit,omitempty"`
	BuildDate                        string   `protobuf:"bytes,3,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	BackingImageManagerApiVersion    int64    `protobuf:"varint,4,opt,name=backing_image_manager_api_version,json=backingImageManagerApiVersion,proto3" json:"backing_image_manager_api_version,omitempty"`
	BackingImageManagerApiMinVersion int64    `protobuf:"varint,5,opt,name=backing_image_manager_api_min_version,json=backingImageManagerApiMinVersion,proto3" json:"backing_image_manager_api_min_version,omitempty"`
	XXX_NoUnkeyedLiteral             struct{} `json:"-"`
	XXX_unrecognized                 []byte   `json:"-"`
	XXX_sizecache                    int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionResponse) GetGitCommit() string {
	if m != nil {
		return m.GitCommit
	}
	return ""
}

func (m *VersionResponse) GetBuildDate() string {
	if m != nil {
		return m.BuildDate
	}
	return ""
}

func (m *VersionResponse) GetBackingImageManagerApiVersion() int64 {
	if m != nil {
		return m.BackingImageManagerApiVersion
	}
	return 0
}

func (m *VersionResponse) GetBackingImageManagerApiMinVersion() int64 {
	if m != nil {
		return m.BackingImageManagerApiMinVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*BackingImageSpec)(nil), "BackingImageSpec")
	proto.RegisterType((*BackingImageStatus)(nil), "BackingImageStatus")
	proto.RegisterType((*BackingImageResponse)(nil), "BackingImageResponse")
	proto.RegisterType((*PullRequest)(nil), "PullRequest")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterMapType((map[string]*BackingImageResponse)(nil), "ListResponse.BackingImagesEntry")
	proto.RegisterType((*SendRequest)(nil), "SendRequest")
	proto.RegisterType((*SyncRequest)(nil), "SyncRequest")
	proto.RegisterType((*OwnershipTransferStartResponse)(nil), "OwnershipTransferStartResponse")
	proto.RegisterMapType((map[string]*BackingImageSpec)(nil), "OwnershipTransferStartResponse.ReadyBackingImagesEntry")
	proto.RegisterType((*OwnershipTransferConfirmRequest)(nil), "OwnershipTransferConfirmRequest")
	proto.RegisterMapType((map[string]*BackingImageSpec)(nil), "OwnershipTransferConfirmRequest.ReadyBackingImagesEntry")
	proto.RegisterType((*VersionResponse)(nil), "VersionResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 864 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x4d, 0x6f, 0xe4, 0x44,
	0x13, 0x8e, 0x33, 0x33, 0xc9, 0x4e, 0x4d, 0xb2, 0xef, 0x6c, 0xbf, 0x21, 0x6b, 0x4d, 0x58, 0x76,
	0x30, 0x5a, 0x11, 0x11, 0xd1, 0x41, 0xc3, 0x0a, 0x56, 0x70, 0x00, 0xf6, 0x43, 0x59, 0x24, 0xa2,
	0x5d, 0x79, 0xd0, 0x2e, 0x37, 0xcb, 0x63, 0xd7, 0x38, 0xcd, 0x8e, 0xbb, 0x4d, 0x77, 0x3b, 0xab,
	0xe1, 0xc0, 0x01, 0xf1, 0x83, 0xf8, 0x35, 0x1c, 0xb9, 0x21, 0xfe, 0x06, 0x6a, 0xb7, 0x3d, 0x1f,
	0x89, 0x3d, 0xe1, 0xc8, 0xad, 0x5d, 0xf5, 0x74, 0x75, 0x55, 0x3d, 0x55, 0x8f, 0xa1, 0x2b, 0xb3,
	0x88, 0x66, 0x52, 0x68, 0x31, 0x38, 0x4a, 0x84, 0x48, 0x66, 0x78, 0x5a, 0x7c, 0x4d, 0xf2, 0xe9,
	0x29, 0xa6, 0x99, 0x9e, 0x5b, 0xa7, 0xf7, 0x0b, 0xf4, 0x1f, 0x87, 0xd1, 0x1b, 0xc6, 0x93, 0x6f,
	0xd3, 0x30, 0xc1, 0x71, 0x86, 0x11, 0x21, 0xd0, 0xe6, 0x61, 0x8a, 0xae, 0x33, 0x74, 0x8e, 0xbb,
	0x7e, 0x71, 0x26, 0x7d, 0x68, 0xe5, 0x72, 0xe6, 0x6e, 0x17, 0x26, 0x73, 0x34, 0xa8, 0x3c, 0x67,
	0xb1, 0xdb, 0xb2, 0x28, 0x73, 0x36, 0x36, 0xc5, 0x7e, 0x46, 0xb7, 0x3d, 0x74, 0x8e, 0x5b, 0x7e,
	0x71, 0x26, 0xef, 0x42, 0x37, 0x66, 0x12, 0x23, 0x2d, 0xe4, 0xdc, 0xed, 0x14, 0xe0, 0xa5, 0xc1,
	0xfb, 0xc3, 0x01, 0xb2, 0x96, 0x80, 0x0e, 0x75, 0xae, 0xc8, 0x01, 0x74, 0x94, 0x0e, 0x75, 0x95,
	0x83, 0xfd, 0x20, 0x47, 0xd0, 0x45, 0x29, 0x85, 0x0c, 0x52, 0x95, 0x94, 0xa9, 0xdc, 0x2a, 0x0c,
	0xe7, 0x2a, 0x21, 0x27, 0x70, 0x47, 0x21, 0x8f, 0x19, 0x4f, 0x02, 0x89, 0x53, 0x94, 0xc8, 0x23,
	0x2c, 0x92, 0xeb, 0xf8, 0xfd, 0xd2, 0xe1, 0x57, 0x76, 0xf2, 0x10, 0x0e, 0x8d, 0x0d, 0x65, 0x90,
	0x86, 0x3c, 0x4c, 0x50, 0x06, 0x61, 0x1c, 0x4b, 0x54, 0xaa, 0x48, 0xbd, 0xeb, 0x1f, 0x58, 0xef,
	0xb9, 0x75, 0x7e, 0x63, 0x7d, 0xe4, 0x23, 0xe8, 0xc7, 0xe2, 0x2d, 0x9f, 0x89, 0x30, 0x7e, 0x29,
	0x45, 0x52, 0xe0, 0x3b, 0xf6, 0x85, 0xab, 0x76, 0xef, 0x37, 0x07, 0x0e, 0x56, 0x0b, 0xf3, 0x51,
	0x65, 0x82, 0x2b, 0x24, 0x0f, 0xa0, 0xad, 0x32, 0x8c, 0x8a, 0xca, 0x7a, 0xa3, 0x3b, 0xf4, 0x6a,
	0xfb, 0xfd, 0xc2, 0x4d, 0x4e, 0x60, 0x47, 0x15, 0xbd, 0x28, 0x0a, 0xed, 0x8d, 0xfe, 0x4f, 0xaf,
	0xb7, 0xc9, 0x2f, 0x21, 0xc4, 0x85, 0xdd, 0x18, 0x67, 0xa8, 0xd1, 0xd2, 0x71, 0xcb, 0xaf, 0x3e,
	0xbd, 0x87, 0xd0, 0x7b, 0x99, 0xcf, 0x66, 0x3e, 0xfe, 0x94, 0xa3, 0xd2, 0xff, 0xf2, 0x71, 0xef,
	0x03, 0xd8, 0x7f, 0x5a, 0x04, 0xa8, 0xee, 0xd5, 0x8c, 0x84, 0x37, 0x04, 0x38, 0x43, 0xbd, 0x09,
	0xf1, 0xbb, 0x03, 0x7b, 0xdf, 0x31, 0xa5, 0x17, 0xb5, 0x9f, 0xc1, 0xed, 0x89, 0x7d, 0x31, 0x60,
	0xe6, 0x49, 0xe5, 0x3a, 0xc3, 0xd6, 0x71, 0x6f, 0x34, 0xa4, 0xab, 0xb0, 0xb5, 0xac, 0xd4, 0x33,
	0xae, 0xe5, 0xdc, 0xdf, 0x9f, 0xac, 0xda, 0x06, 0xaf, 0xd7, 0xa7, 0xc6, 0x82, 0xcc, 0x90, 0xbe,
	0xc1, 0x79, 0x99, 0x82, 0x39, 0x92, 0x13, 0xe8, 0x5c, 0x86, 0xb3, 0x1c, 0xcb, 0x26, 0xbe, 0x43,
	0xeb, 0x28, 0xf1, 0x2d, 0xe6, 0x8b, 0xed, 0x47, 0x8e, 0xf7, 0x35, 0xf4, 0xc6, 0xc8, 0xe3, 0x0d,
	0x55, 0x91, 0x7b, 0x00, 0x5a, 0x2c, 0xe6, 0xc5, 0x8e, 0x61, 0x57, 0x8b, 0x72, 0x48, 0x0c, 0xf1,
	0xbd, 0xf1, 0x9c, 0x47, 0x55, 0x88, 0xaf, 0x80, 0xac, 0xd5, 0x1c, 0x6c, 0x26, 0xa0, 0x3f, 0xb9,
	0xba, 0x8e, 0x47, 0xd0, 0x9d, 0x4a, 0x91, 0x06, 0x17, 0x42, 0xe9, 0x6a, 0xea, 0x8d, 0xe1, 0xb9,
	0x50, 0x9a, 0xdc, 0x85, 0x5d, 0x2d, 0xac, 0xcb, 0x2e, 0xe2, 0x8e, 0x16, 0xc6, 0xe1, 0xfd, 0xe5,
	0xc0, 0x7b, 0x2f, 0xde, 0x72, 0x94, 0xea, 0x82, 0x65, 0xdf, 0xcb, 0x90, 0xab, 0x29, 0xca, 0xb1,
	0x0e, 0xe5, 0x92, 0x0d, 0x06, 0x07, 0x12, 0xc3, 0x78, 0x1e, 0xd4, 0x72, 0xf2, 0x39, 0xdd, 0x7c,
	0x9d, 0xfa, 0xe6, 0x6e, 0x0d, 0x55, 0x44, 0x5e, 0x73, 0x0c, 0x7e, 0x80, 0xbb, 0x0d, 0xf0, 0x1a,
	0xd2, 0x3e, 0x5c, 0x27, 0xad, 0xa6, 0x49, 0x2b, 0x84, 0xfd, 0xed, 0xc0, 0xfd, 0x6b, 0x89, 0x3e,
	0x11, 0x7c, 0xca, 0x64, 0x5a, 0x51, 0xf0, 0xe3, 0xc6, 0x42, 0x1f, 0xd1, 0x1b, 0xee, 0xff, 0x47,
	0x2a, 0xfd, 0x75, 0x1b, 0xfe, 0xf7, 0x0a, 0xa5, 0x62, 0x82, 0x2f, 0x28, 0x74, 0x61, 0xf7, 0xd2,
	0x9a, 0xca, 0xb0, 0xd5, 0xa7, 0x91, 0xdd, 0x84, 0xe9, 0x27, 0x22, 0x4d, 0x59, 0x35, 0x35, 0x4b,
	0x83, 0xf1, 0x4e, 0x72, 0x36, 0x8b, 0x9f, 0x1a, 0x8d, 0xb5, 0x83, 0xb3, 0x34, 0x90, 0xe7, 0xf0,
	0xfe, 0xfa, 0xc8, 0x2e, 0x44, 0x32, 0x63, 0x41, 0xf5, 0x9e, 0xd5, 0xf8, 0x7b, 0xab, 0xe3, 0x5a,
	0xc9, 0x65, 0xc6, 0xca, 0x3c, 0xc9, 0x0b, 0x78, 0xd0, 0x1c, 0x29, 0x65, 0x7c, 0x11, 0xad, 0x53,
	0x44, 0x1b, 0xd6, 0x47, 0x3b, 0x67, 0xbc, 0x0c, 0x38, 0xfa, 0xb3, 0x0d, 0x83, 0xc7, 0xd7, 0x41,
	0x63, 0x94, 0x97, 0x2c, 0x42, 0xf2, 0x31, 0xb4, 0x8d, 0xdc, 0x91, 0x3d, 0xba, 0xa2, 0x7a, 0x83,
	0xfa, 0xb5, 0xf7, 0xb6, 0x0c, 0xdc, 0xac, 0x2a, 0xd9, 0xa3, 0x2b, 0x1b, 0xdb, 0x0c, 0xa7, 0xd0,
	0x36, 0xe2, 0x60, 0xe0, 0x4b, 0x8d, 0x18, 0x1c, 0x52, 0xfb, 0x83, 0xa5, 0xd5, 0x0f, 0x96, 0x3e,
	0x33, 0x3f, 0x58, 0x6f, 0x8b, 0x8c, 0x60, 0xc7, 0xca, 0x28, 0xb9, 0x4d, 0xd7, 0xf4, 0x74, 0xc3,
	0x9d, 0x13, 0x68, 0x9d, 0xa1, 0x26, 0x3d, 0xba, 0xd4, 0xd6, 0xe6, 0x84, 0x4e, 0xa1, 0x6d, 0x84,
	0x93, 0x34, 0x84, 0x1b, 0xec, 0xaf, 0xe9, 0xaa, 0xb7, 0x45, 0xc6, 0x70, 0x58, 0xbf, 0xd5, 0x8d,
	0x21, 0xee, 0xdf, 0x20, 0x03, 0xde, 0x16, 0x79, 0x05, 0x6e, 0xd3, 0x06, 0x91, 0xe1, 0x4d, 0xcb,
	0xb5, 0xa1, 0x15, 0x9f, 0x01, 0x94, 0xb4, 0x9b, 0x8e, 0x34, 0x25, 0xd8, 0xa7, 0x57, 0x97, 0xe2,
	0x4b, 0xe8, 0xbc, 0x0e, 0x75, 0x74, 0xd1, 0x78, 0xa5, 0xf1, 0xc9, 0x4f, 0x9c, 0xc9, 0x4e, 0x61,
	0xfb, 0xf4, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x46, 0x70, 0x8f, 0x41, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackingImageManagerServiceClient is the client API for BackingImageManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackingImageManagerServiceClient interface {
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*BackingImageResponse, error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*BackingImageResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BackingImageResponse, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error)
	OwnershipTransferStart(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*OwnershipTransferStartResponse, error)
	OwnershipTransferConfirm(ctx context.Context, in *OwnershipTransferConfirmRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	VersionGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	Watch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BackingImageManagerService_WatchClient, error)
}

type backingImageManagerServiceClient struct {
	cc *grpc.ClientConn
}

func NewBackingImageManagerServiceClient(cc *grpc.ClientConn) BackingImageManagerServiceClient {
	return &backingImageManagerServiceClient{cc}
}

func (c *backingImageManagerServiceClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*BackingImageResponse, error) {
	out := new(BackingImageResponse)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*BackingImageResponse, error) {
	out := new(BackingImageResponse)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*BackingImageResponse, error) {
	out := new(BackingImageResponse)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) OwnershipTransferStart(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*OwnershipTransferStartResponse, error) {
	out := new(OwnershipTransferStartResponse)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/OwnershipTransferStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) OwnershipTransferConfirm(ctx context.Context, in *OwnershipTransferConfirmRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/OwnershipTransferConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) VersionGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/BackingImageManagerService/VersionGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backingImageManagerServiceClient) Watch(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (BackingImageManagerService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BackingImageManagerService_serviceDesc.Streams[0], "/BackingImageManagerService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &backingImageManagerServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BackingImageManagerService_WatchClient interface {
	Recv() (*empty.Empty, error)
	grpc.ClientStream
}

type backingImageManagerServiceWatchClient struct {
	grpc.ClientStream
}

func (x *backingImageManagerServiceWatchClient) Recv() (*empty.Empty, error) {
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BackingImageManagerServiceServer is the server API for BackingImageManagerService service.
type BackingImageManagerServiceServer interface {
	Pull(context.Context, *PullRequest) (*BackingImageResponse, error)
	Sync(context.Context, *SyncRequest) (*BackingImageResponse, error)
	Send(context.Context, *SendRequest) (*empty.Empty, error)
	Delete(context.Context, *DeleteRequest) (*empty.Empty, error)
	Get(context.Context, *GetRequest) (*BackingImageResponse, error)
	List(context.Context, *empty.Empty) (*ListResponse, error)
	OwnershipTransferStart(context.Context, *empty.Empty) (*OwnershipTransferStartResponse, error)
	OwnershipTransferConfirm(context.Context, *OwnershipTransferConfirmRequest) (*empty.Empty, error)
	VersionGet(context.Context, *empty.Empty) (*VersionResponse, error)
	Watch(*empty.Empty, BackingImageManagerService_WatchServer) error
}

// UnimplementedBackingImageManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBackingImageManagerServiceServer struct {
}

func (*UnimplementedBackingImageManagerServiceServer) Pull(ctx context.Context, req *PullRequest) (*BackingImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) Sync(ctx context.Context, req *SyncRequest) (*BackingImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) Send(ctx context.Context, req *SendRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) Get(ctx context.Context, req *GetRequest) (*BackingImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) List(ctx context.Context, req *empty.Empty) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) OwnershipTransferStart(ctx context.Context, req *empty.Empty) (*OwnershipTransferStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OwnershipTransferStart not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) OwnershipTransferConfirm(ctx context.Context, req *OwnershipTransferConfirmRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OwnershipTransferConfirm not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) VersionGet(ctx context.Context, req *empty.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VersionGet not implemented")
}
func (*UnimplementedBackingImageManagerServiceServer) Watch(req *empty.Empty, srv BackingImageManagerService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterBackingImageManagerServiceServer(s *grpc.Server, srv BackingImageManagerServiceServer) {
	s.RegisterService(&_BackingImageManagerService_serviceDesc, srv)
}

func _BackingImageManagerService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).List(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_OwnershipTransferStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).OwnershipTransferStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/OwnershipTransferStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).OwnershipTransferStart(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_OwnershipTransferConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnershipTransferConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).OwnershipTransferConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/OwnershipTransferConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).OwnershipTransferConfirm(ctx, req.(*OwnershipTransferConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_VersionGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackingImageManagerServiceServer).VersionGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BackingImageManagerService/VersionGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackingImageManagerServiceServer).VersionGet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackingImageManagerService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackingImageManagerServiceServer).Watch(m, &backingImageManagerServiceWatchServer{stream})
}

type BackingImageManagerService_WatchServer interface {
	Send(*empty.Empty) error
	grpc.ServerStream
}

type backingImageManagerServiceWatchServer struct {
	grpc.ServerStream
}

func (x *backingImageManagerServiceWatchServer) Send(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

var _BackingImageManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BackingImageManagerService",
	HandlerType: (*BackingImageManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pull",
			Handler:    _BackingImageManagerService_Pull_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _BackingImageManagerService_Sync_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _BackingImageManagerService_Send_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BackingImageManagerService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BackingImageManagerService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BackingImageManagerService_List_Handler,
		},
		{
			MethodName: "OwnershipTransferStart",
			Handler:    _BackingImageManagerService_OwnershipTransferStart_Handler,
		},
		{
			MethodName: "OwnershipTransferConfirm",
			Handler:    _BackingImageManagerService_OwnershipTransferConfirm_Handler,
		},
		{
			MethodName: "VersionGet",
			Handler:    _BackingImageManagerService_VersionGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _BackingImageManagerService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc.proto",
}
