#!/bin/bash
set -ex

source $(dirname $0)/version

LINKFLAGS="-X main.Version=$VERSION
           -X main.GitCommit=$GITCOMMIT
           -X main.BuildDate=$BUILDDATE"
[ "$(uname)" != "Darwin" ] && OTHER_LINKFLAGS="-extldflags -static"

cd $(dirname $0)/..

mkdir -p bin

archs=("amd64" "arm64")
for arch in "${archs[@]}"; do
    CGO_ENABLED=0 GOARCH="$arch" go build -o "bin/backing-image-manager-$arch" -ldflags "$LINKFLAGS $OTHER_LINKFLAGS"
done
