#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

PROJECT=`basename "$PWD"`

if [ ! -x ./bin/longhorn ]; then
    ./scripts/build
fi

cp -r bin package/

APIVERSION=`./bin/backing-image-manager version --client-only|jq ".clientVersion.backingImageManagerAPIVersion"`
TAG="v${APIVERSION}_`date -u +%Y%m%d`"
REPO=${REPO:-longhornio}
IMAGE=${REPO}/${PROJECT}:${TAG}

buildx build --load --no-cache -t ${IMAGE} -f package/Dockerfile .

echo Built ${IMAGE}

echo ${IMAGE} > ./bin/latest_image
